/*
link: aff link 
*/
var mgg_ghim = [
{
    value: ' Giảm 30K cho đơn từ 179k',
    minspend: '',
    tag: 'Highlands Coffee',
    link: 'https://shorten.asia/yWcZW9UZ',
    start_time: '2023/09/05',
    end_time: '2023/09/30',
    remain: 'Không giới hạn',
    image: 'https://cdn.haitrieu.com/wp-content/uploads/2022/03/highlands-coffee-red-logo.png',
    detail: 'B1: Nhấn Đến banner để lưu mã. => B2:Chọn mã muốn lấy và nhấn vào mã đó. => B3: Chụp ảnh màn hình voucher và áp tại điểm bán của Highlands',
  },
  {
    value: ' Giảm 20K cho đơn từ 139k',
    minspend: '',
    tag: 'Highlands Coffee',
    link: 'https://shorten.asia/yWcZW9UZ',
    start_time: '2023/09/05',
    end_time: '2023/09/30',
    remain: 'Không giới hạn',
    image: 'https://cdn.haitrieu.com/wp-content/uploads/2022/03/highlands-coffee-red-logo.png',
    detail: 'B1: Nhấn Đến banner để lưu mã. => B2:Chọn mã muốn lấy và nhấn vào mã đó. => B3: Chụp ảnh màn hình voucher và áp tại điểm bán của Highlands',
  },
  {
    value: ' Mua 2 được 3',
    minspend: '',
    tag: 'Highlands Coffee',
    link: 'https://shorten.asia/yWcZW9UZ',
    start_time: '2023/09/05',
    end_time: '2023/09/30',
    remain: 'Không giới hạn',
    image: 'https://cdn.haitrieu.com/wp-content/uploads/2022/03/highlands-coffee-red-logo.png',
    detail: 'B1: Nhấn Đến banner để lưu mã. => B2:Chọn mã muốn lấy và nhấn vào mã đó. => B3: Chụp ảnh màn hình voucher và áp tại điểm bán của Highlands',
  },
]



/*
     {
    value: ' Giảm 20K đơn 99K ',
    minspend: 'Thời trang Lazada',
    tag: 'Lazada độc quyền',
    link: 'https://shorten.asia/syyc5XF8',
    start_time: '2023/05/25',
    end_time: '2023/06/10 23:59',
    remain: '30',
    image: ' https://i.imgur.com/gXA8JxH.png ',
    detail: '   Code 20k/99k Fashion độc quyền Trùm Giảm Giá ',
code: 'Lazlook2095upi7',
  },
  {
    value: 'Giảm 50K cho đơn từ 399k',
    minspend: 'Mọi đơn hàng',
    tag: 'Unica độc quyền',
    link: 'https://shorten.asia/NWgDee8C',
    start_time: '2023/01/01',
    end_time: '2023/06/30 23:59',
    remain: '799',
    image: ' https://static.accesstrade.vn/adv/img/logo/unica.jpg ',
    detail: '   Code 50K/399k toàn sàn độc quyền Trùm Giảm Giá ',
code: 'MBUNICA50K',
  },
    {
    value: 'Giảm 100K cho đơn từ 599k',
    minspend: 'Mọi đơn hàng',
    tag: 'Unica độc quyền',
    link: 'https://shorten.asia/C61X9J1G',
    start_time: '2023/01/01',
    end_time: '2023/06/30 23:59',
    remain: '358',
    image: ' https://static.accesstrade.vn/adv/img/logo/unica.jpg ',
    detail: '   Code 100K/599k toàn sàn độc quyền Trùm Giảm Giá ',
code: 'MBUNICA100K',
  },
  {
    value: ' Giảm 25K đơn 99K ',
    minspend: 'Toàn sàn',
    tag: 'Lazada độc quyền',
    link: 'https://shorten.asia/P7fhHcZV',
    start_time: '2023/05/25',
    end_time: '2023/06/10 23:59',
    remain: '30',
    image: ' https://i.imgur.com/gXA8JxH.png ',
    detail: '   Code 25k/99k toàn sàn độc quyền Trùm Giảm Giá ',
code: 'LazT52521ipex',
  },
*/
